

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb+srv://srimali:123@cluster0.ijjxw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo

  frontend:
    build: ./food-blog-app
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"